#!/bin/bash
# NoppoAIHub エディタ - クイックスタートガイド

echo "🚀 NoppoAIHub エディタ - セットアップガイド"
echo "=========================================="
echo ""
echo "📋 実装完了機能："
echo "  ✅ ターミナル対話入力 (Python, npm, node)"
echo "  ✅ データセット選択と自動学習コード生成"
echo "  ✅ AI プロジェクト初期設定ウィザード"
echo "  ✅ リアルタイム学習メトリクス表示"
echo ""
echo "📁 ファイル構成："
echo ""
ls -la js/editor/ | grep -E "\.js$" | awk '{print "  " $NF}'
echo ""
echo "🧪 テスト方法："
echo ""
echo "1. ローカルサーバーで起動："
echo "   python -m http.server 8000"
echo ""
echo "2. ブラウザで開く:"
echo "   http://localhost:8000/index.html"
echo ""
echo "3. プロジェクトを開き、editor.html にアクセス"
echo ""
echo "4. Inspector タブで 3つ機能をテスト："
echo "   📋 File Inspector"
echo "   📊 Dataset & Training"
echo "   ⚙️ Project Setup"
echo ""
echo "✨ 完了！"
